#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Есть словарь кодов товаров

goods = {
    'Лампа': '12345',
    'Стол': '23456',
    'Диван': '34567',
    'Стул': '45678',
}

# Есть словарь списков количества товаров на складе.

store = {
    '12345': [
        {'quantity': 27, 'price': 42},
    ],
    '23456': [
        {'quantity': 22, 'price': 510},
        {'quantity': 32, 'price': 520},
    ],
    '34567': [
        {'quantity': 2, 'price': 1200},
        {'quantity': 1, 'price': 1150},
    ],
    '45678': [
        {'quantity': 50, 'price': 100},
        {'quantity': 12, 'price': 95},
        {'quantity': 43, 'price': 97},
    ],
}

# Рассчитать на какую сумму лежит каждого товара на складе
# например для ламп

lamps_cost = store[goods['Лампа']][0]['quantity'] * store[goods['Лампа']][0]['price']
# или проще (/сложнее ?)
lamp_code = goods['Лампа']
lamps_item = store[lamp_code][0]
lamps_quantity = lamps_item['quantity']
lamps_price = lamps_item['price']
lamps_cost = lamps_quantity * lamps_price
print('Лампа -', lamps_quantity, 'шт, стоимость', lamps_cost, 'руб')

# Вывести стоимость каждого вида товара на складе:
# один раз распечать сколько всего столов и их общая стоимость,
# один раз распечать сколько всего стульев и их общая стоимость,
#   и т.д. на складе
# Формат строки <товар> - <кол-во> шт, стоимость <общая стоимость> руб

# WARNING для знающих циклы: БЕЗ циклов. Да, с переменными; да, неэффективно; да, копипаста.
# Это задание на ручное вычисление - что бы потом понять как работают циклы и насколько с ними проще жить.

# TODO здесь ваш код
table_code = goods['Стол']
tables_item = store[table_code][0]
tables_quantity = tables_item['quantity']
tables_price = tables_item['price']
table_cost = tables_quantity * tables_price

tables1_item = store[table_code][1]
tables1_quantity = tables1_item['quantity']
tables1_price = tables1_item['price']
table1_cost = tables1_quantity * tables1_price
print('Стол -', tables_quantity + tables1_quantity, 'шт, стоимость', table_cost + table1_cost, 'руб')

sofa_code = goods['Диван']
sofas_item = store[sofa_code][0]
sofas_quantity = sofas_item['quantity']
sofas_price = sofas_item['price']
sofa_cost = sofas_quantity * sofas_price

sofa1_item = store[sofa_code][1]
sofas1_quantity = sofa1_item['quantity']
sofas1_price = sofa1_item['price']
sofa1_cost = sofas1_quantity * sofas1_price
print('Диван -', sofas_quantity + sofas1_quantity, 'шт, стоимость', sofa_cost + sofa1_cost, 'руб')

chair_code = goods['Стул']
chairs_item = store[chair_code][0]
chairs_quantity = chairs_item['quantity']
chairs_price = chairs_item['price']
chair_cost = chairs_quantity * chairs_price

chair1_item = store[chair_code][1]
chairs1_quantity = chair1_item['quantity']
chairs1_price = chair1_item['price']
chair1_cost = chairs1_quantity * chairs1_price

chair2_item = store[chair_code][2]
chairs2_quantity = chair2_item['quantity']
chairs2_price = chair2_item['price']
chair2_cost = chairs2_quantity * chairs2_price
print('Стул -', chairs_quantity + chairs1_quantity + chairs2_quantity, 'шт, стоимость', chair_cost + chair1_cost + chair2_cost , 'руб')
